＃文件：.github / workflows / repo-sync.yml
名称：🔄自动同步🔄
上：
  时间表：
    -cron：“ 0/20 1-4,11-14 * * *”
  工作流程调度：
  看：
    类型：开始
  repository_dispatch：
    类型：repo-sync
职位：
  回购同步：
    环境：
      PAT：$ {{github.event.client_payload.PAT || secrets.PAT}}＃此处PAT需要申请，教程详见：https：//www.jianshu.com/p/bb82b3ad1d11
      dst_key：$ {{secrets.GITEE_PRIVATE_KEY}}＃我自己同步到gitee使用，其他人可忽略
    运行：ubuntu-latest
    如果：github.event.repository.owner.id == github.event.sender.id
    脚步：
      -用途：actions / checkout @ v2
        与：
          持久凭证：false

      -名称：开始🔄自动同步🔄
        用途：repo-sync / github-sync @ v2
        如果：env.PAT
        与：
          source_repo：“ https://github.com/shuye72/MyActions.git”
          source_branch：“主要”
          destination_branch：“主要”
          github_token：$ {{github.event.client_payload.PAT || secrets.PAT}}
      ＃我自己同步到gitee使用，其他人可忽略
      -名称：同步github-> gitee
        用途：Yikun / hub-mirror-action @ master
        如果：env.dst_key
        与：
          src：github / shuye72
          dst：gitee / shuye72
          static_list：“ MyActions”
          dst_key：$ {{secrets.GITEE_PRIVATE_KEY}}
          dst_token：$ {{secrets.GITEE_TOKEN}}
